# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=10, verbose_name='栏目名称')),
                ('parent', models.CharField(max_length=3, verbose_name='父级栏目')),
                ('is_publish', models.CharField(max_length=1, verbose_name='是否发布')),
                ('add_time', models.DateField(verbose_name='添加日期')),
                ('is_valid', models.CharField(max_length=1, verbose_name='是否有效')),
            ],
        ),
    ]
