# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='add_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='add_time',
            field=models.DateField(auto_now_add=True, verbose_name='添加日期'),
        ),
    ]
