# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_delete_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=10, verbose_name='横幅名称')),
                ('banner_url', models.CharField(max_length=50, verbose_name='链接地址')),
                ('banner_image', models.FileField(upload_to='', verbose_name='图片文件')),
                ('banner_txt', models.CharField(max_length=50, verbose_name='描述文字')),
                ('add_date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
