# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 05:32
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='is_publish',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='parent',
        ),
        migrations.AddField(
            model_name='channel',
            name='is_nav',
            field=models.CharField(choices=[('0', '是'), ('1', '否')], default='0', max_length=1, verbose_name='导航菜单'),
        ),
        migrations.AddField(
            model_name='channel',
            name='order_position',
            field=models.IntegerField(default=0, verbose_name='序列号'),
        ),
        migrations.AlterField(
            model_name='article',
            name='add_user',
            field=models.CharField(max_length=15, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=ckeditor.fields.RichTextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_image',
            field=models.ImageField(upload_to='', verbose_name='图片文件'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='is_valid',
            field=models.CharField(choices=[('0', '是'), ('1', '否')], max_length=1, verbose_name='是否有效'),
        ),
    ]
