# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20160602_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_single_page',
            field=models.CharField(choices=[('1', '是'), ('0', '否')], default='0', max_length=1, verbose_name='单页栏目'),
        ),
        migrations.AlterField(
            model_name='article',
            name='add_date',
            field=models.DateField(auto_now_add=True, verbose_name='添加日期'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='is_nav',
            field=models.CharField(choices=[('1', '是'), ('0', '否')], default='1', max_length=1, verbose_name='导航菜单'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='is_valid',
            field=models.CharField(choices=[('1', '是'), ('0', '否')], default='1', max_length=1, verbose_name='是否有效'),
        ),
    ]
