# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20160603_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='allow_comment',
        ),
    ]
