# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_remove_article_allow_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='文章图片'),
        ),
    ]
