# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_article_article_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_icon',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='文章图片'),
        ),
    ]
