# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20160605_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visit',
            field=models.IntegerField(default=0, verbose_name='访问量'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_icon',
            field=models.ImageField(null=True, upload_to='article', verbose_name='文章图片'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_image',
            field=models.ImageField(upload_to='banner', verbose_name='图片文件'),
        ),
    ]
