# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160705_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Channel', verbose_name='所属栏目'),
        ),
    ]
